<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple menu soup</title>
    <link rel="stylesheet" href="style1.css">
</head>
<body>
    <div class="pengantar2">
        <h2 style="text-align: center;">Selamat Datang Simple Menu Soup</h2>
                <p>Welcome!<b>Pengertian</b>Tentang. Soup adalah sajian yang di dalamnya berisi berbagai bahan makanan dan terdapat penambahan kaldu untuk meningkatkan cita rasa, aroma hingga warnanya. Bahan soup yang variatif, mengandung beragam gizi yang dibutuhkan tubuh. Kaldunya pun bisa didapat dari ayam, daging atau bahkan ikan.</p>
                <p>Di bawah ini ada beberapa Menu Soup Simple yang anda bisa coba.</p>

    <div class="Soup sosis">
        <h1 style="text-align: center;">1.Soup jagung sosis</h1>
        <img src="images/sop jagung.jpg" alt="Soup Jagung Sosis">
        <h3 style="text-align: center;">Bahan-bahan pembuatan</h3>
        <p>- 1 liter air
        <p>- 3 buah sosis (potong)
        <p>- 2 buah jagung (pipil)
        <p>- 1 buah wortel (potong)
        <p>- 10 buah telur puyuh (rebus dan kupas kulitnya)
        <p>- 4 siung bawang putih
        <p>- 1/4 buah bawang bombai
        <p>- 1 sdt mentega
        <p>- 1/2 sdm garam
        <p>- 1/2 sdt merica
        <p>- 2 batang daun bawang (iris tipis)
            <h2 style="text-align: center;">Cara Menyajikan</h2>
                <p>1. Didihkan air, kemudian masukkan semua bahan (kecuali telur puyuh) dan masak hingga sayuran matang.</p>
                <p>2. Beri mentega, garam, merica, dan daun bawang. Kemudian masukkan telur puyuh dan masak hingga matang.</p>
                <p>2. Sup jagung sosis siap disajikan.</p>
    </div>

    <div class="Sop sayur">
        <h1 style="text-align: center;">2.Soup sayur</h1>
        <img src="images/sop sayur.png" alt="">
        <h4>Kali ini kita akan beralih ke soup sayur simple, tersebut biasa yang kita sering jumpai di warung ataupun di restoran.</h4>
        <h3 style="text-align: center;">Bahan-bahan</h3>
        <p>- 1 buah kentang (potong)
        <p>- 2 buah wortel (potong)
        <p>- buncis
        <p>- kubis
        <p>- 3 siung bawang putih (geprek)
        <p>- 2 butir bawang merah (geprek)
        <p>- 2 buah daun bawang (potong panjang)
        <p>- 3 batang seledri (potong)
        <p>- 1/2 sdt kaldu bubuk
        <p>- gula
        <p>- garam
        <p>- merica
        <p>- 2 sdm minyak
        <p>- 400 ml air
        <p>- bawang goreng
            <h3 style="text-align: center;">Proses Pembuatan</h3>
            <p>1. Panaskan minyak, tumis bawang hingga harum.2. Masukan air dan tunggu hingga mendidih. Lalu masukkan kentang dan wortel.3. Tambahkan gula, garam, merica, dan kaldu bubuk. Jika kentang sudah mulai empuk, masukan buncis dan kubis, tunggu hingga mendidih. Kemudian matikan api.4. Pindahkan sop dalam wadah, lalu taburi sop dengan daun bawang, seledri, dan bawang goreng. Sop sayur siap disajikan.</p>
    </div>

    <div class="Soup Kepiting Tofu">
        <h1 style="text-align: center;">3.Soup Kepiting Tofu</h1>
        <img src="images/sop kepiting.png" alt="Soup Kepiting Tofu">
        <h3 style="text-align: center;">Bahan-bahan</h3>
        <div style="text-align: center;"><p>
            <p>- 600ml air
            <p>- 100gr daging kepiting
            <p>- 50gr jagung (pipil)
            <p>- 1 buah tofu (potong)
            <p>- 1 butir telur
            <p>- 2 siung bawang putih (geprek dan cacah)
            <p>- 1/4 buah bawang bombay (potong dadu)
            <p>- 2 sdm tepung maizena (larutkan dengan air)
            <p>- 2 batang seledri
            <p>- 2 sdm tepung maizena (larutkan dengan air)
            <p>- 1 sdm minyak wijen
            <p>- lada bubuk
            <p>- kaldu jamur
            <p>- garam
            <p>- gula pasir
            </p>
        <h3>Cara Penyajian!</h3>
        <ol>
            <li>Tumis bawang putih dan bawang bombay sampai harum, lalu masukkan daging kepiting dan jagung pipil. Masak sambil diaduk-aduk.</li>
            <li>Tambahkan air, masak sampai mendidih. Setelah itu, masukkan tofu, beri garam, kaldu jamur, minyak wijen, lada bubuk, dan gula pasir.</li>
            <li>Tambahkan larutan maizena dan aduk-aduk kembali. Lalu kocok telur, tuang perlahan ke dalam sop sambil diaduk-aduk sopnya.</li>
            <li>Beri potongan batang seledri, masak sebentar.</li>
            <li>Sop kepiting tofu siap disajikan.</li>
        </ol>
        </div>






        

</html>