<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style1.css">
</head>
<body>
    <div class="Pengantar">
        <h3>Selamat datang di resep mie simple!</h3>
        <p>Welcome!<b> Rumah </b>Halaman. Mie adalah makanan yang terbuat dari adonan tepung, biasanya terigu, yang dibentuk menjadi berbagai bentuk dan ukuran, kemudian dimasak dengan cara direbus, dikukus, atau digoreng. Mie sangat populer di berbagai belahan dunia, termasuk Indonesia, dan seringkali menjadi alternatif pengganti nasi.</p>
        <p>Nah, berikut di bawah ini ada beberapa mie yang bisa kamu coba di rumah ataupun di luar mie ini bisa jadi pilihan terbaik mu!<p/>
</div>


    <div class="box-gamok">
        <h1>Mie Gamok</h1>
    </div>
</body>
</html>